accounts/urls.py
from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView,
)

app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
]

app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView

admin.site.site_header = 'Misfit Admin'                    # default: "Django Administration"
admin.site.index_title = 'Misfit Administration'           # default: "Site administration"
admin.site.site_title = 'Misfit Online Request Management' # default: "Django site admin"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexPageView.as_view(), name='index'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include('accounts.urls')),
    path('erequest/', include('erequest.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

erequest/urls.py
from django.urls import path

from .views import *
from .pdf_view import *

app_name = 'erequest'

urlpatterns = [
    path('list', ErequestListView.as_view(), name='erequest_post_list'),
    path('view/<int:pk>', ErequestDetailView.as_view(), name='erequest_post_detail'),
    path('new', ErequestCreateView.as_view(), name='erequest_post_create'),
    path('edit/<int:pk>', ErequestUpdateView.as_view(), name='erequest_post_update'),
    path('delete/<int:pk>', ErequestDeleteView.as_view(), name='request_post_delete'),

    path('details/view/<int:pk>', ErequestDetailsDetailView.as_view(), name='erequest_details_post_detail'),
    path('details/delete/<int:pk>', ErequestDetailsDeleteView.as_view(), name='request_details_post_delete'),

    path('pdf', html_to_pdf_view, name='request_pdf_download'),

]

content/templates/layouts/default/page.html
<!DOCTYPE html>
{% load staticfiles %}
{% load bootstrap4 %}
{% load i18n %}
{% load template_filters %}

{% get_current_language as language_code %}
<html lang="{{ language_code }}">
<head>
    <style>
    .footer {
       <!--position: fixed;-->
       left: 0;
       bottom: 0;
       width: 100%;
       <!--background-color: green;-->
       color: white;
       text-align: center;
    }
    </style>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Misfit Online Request Management">
    <meta name="author" content="Yehor Smoliakov">

    <link rel="icon" href="{% static 'small-logo.png' %}">
    <!--<link rel="icon" href="{% static 'favicon.ico' %}">-->

    <title>Misfit Technology Online Request Management</title>

    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <script src="{% static 'vendor/jquery/jquery-3.3.1.min.js' %}"></script>
    <!--<script src="sweetalert2.all.min.js"></script>-->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.26.12/dist/sweetalert2.all.min.js"></script>

</head>

<body>


<nav class="navbar navbar-expand-md navbar-dark bg-dark static-top">

    <a class="navbar-brand" href="/"><b>{% trans 'eRequesting' %}</b></a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}
                {% if request.user.user_type|check_user_type:"Employee" %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'erequest:erequest_post_list' %}?status=Open">{% trans 'My Open Request' %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'erequest:erequest_post_list' %}?status=HR Reviewed">{% trans 'My Reviewed Request' %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'erequest:erequest_post_list' %}?status=Processed">{% trans 'My Processed Request' %}</a>
                    </li>


                {% elif request.user.user_type|check_user_type:"HR" %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'erequest:erequest_post_list' %}?status=Open">{% trans 'Open Request' %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'erequest:erequest_post_list' %}?status=HR Reviewed">{% trans 'Reviewed Request' %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'erequest:erequest_post_list' %}?status=Processed">{% trans 'Processed Request' %}</a>
                    </li>


                {% elif request.user.user_type|check_user_type:"Management" %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'erequest:erequest_post_list' %}?status=HR Reviewed">{% trans 'Reviewed Request' %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'erequest:erequest_post_list' %}?status=Processed">{% trans 'Processed Request' %}</a>
                    </li>
                {% endif %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:change_password' %}">{% trans 'Change Password' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:change_profile' %}">{% trans 'Change Profile' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:change_email' %}">{% trans 'Change Email' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:log_out' %}">{% trans 'Log Out' %}</a>
                </li>

            {% endif %}

        </ul>

        {% if not request.user.is_authenticated %}
            <ul class="navbar-nav">
               <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:log_in' %}">{% trans 'Log In' %}</a>
               </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:sign_up' %}">{% trans 'Create an Account' %}</a>
                </li>
            </ul>
        {% endif %}
    </div>

</nav>

<!--<div class="container-fluid mt-5 mb-5">-->
<div class="container mt-5  mb-5">

    {% bootstrap_messages %}

    {% block content %}
        No content.
    {% endblock %}

</div>


<div class="footer">
  <p>&copy; Copyright 2018  <b>Misfit Technologies</b> - All Rights Reserved</p>
</div>


<script src="{% static 'vendor/popper/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

</body>
</html>